version: '3.8'

# 테스트할때 사용하기 위함입니다.
services:
  postgres:
    image: postgres:18
    container_name: "postgres_database"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "church_accounting"
      TZ: "Asia/Seoul"
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./postgres_setting.sh:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    container_name: "redis-cache"
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./redis-data:/data
    restart: unless-stopped

  migrate:
    build: .
    container_name: "database_migrate"
    command: sh -c "uv run /app/src/main/common/database/wait_for_postgres.py && uv run alembic upgrade head"
    depends_on:
      - postgres

  web:
    build: .
    container_name: "church_accounting_web"
    command: ["uv", "run", "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "src.main.main:app", "--bind", "0.0.0.0:8000", "--workers", "2", "--reload"]
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
    depends_on:
      - migrate
      - postgres
      - redis
    restart: unless-stopped

  