[project]
name = "web-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.122.0",
    "psycopg>=3.2.13",
    "sqlalchemy>=2.0.44",
]
